sudo: false
cache: bundler

before_install:
  - gem update bundler

rvm:
  - "2.4.9"
  - "2.5.7"
  - "2.6.5"
  - "2.7.0"
  - "3.0.0"
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile

matrix:
  exclude:
    - rvm: 2.4.9
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 3.0.0
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 3.0.0
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 3.0.0
      gemfile: gemfiles/rails_5.2.gemfile

script: "bundle exec rake spec"
